### ISSUE TITLE
Delay in updates compared to full map

### ISSUE THREAD

**Issue by Stanzilla** [kemayo/wow-questpointer#1]
After completing a quest step, QuestPointer has a very long delay in updating the minimap blog compared to the World Map. Maybe missing an event?

https://i.imgur.com/UUiUNzU.jpg

**Comment by kemayo** [comment]
I had a check which was suppressing updates while the world map was open. I amended it in 6480cc66ee28bb5c48571a8aaac49b4840e8a1df to be more permissive.
