### ISSUE TITLE
LUA errors since 10.1.5

### ISSUE THREAD

**Issue by allogator** [kemayo/wow-questpointer#5]
750x QuestPointer/QuestPointer.lua:167: attempt to call global 'QuestPOI_GetButton' (a nil value)
[string "@QuestPointer/QuestPointer.lua"]:167: in function `UpdateLogPOIs'
[string "@QuestPointer/QuestPointer.lua"]:114: in function <QuestPointer/QuestPointer.lua:94>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `AddQuestWatch'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:916: in function <...zzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua:896>

Locals:
self = <table> {
 PLAYER_LOGOUT = <function> defined @QuestPointer/QuestPointer.lua:64
 defaults = <table> {
 }
 UpdateGlow = <function> defined @QuestPointer/QuestPointer.lua:385
 GetWorldQuestButton = <function> defined @QuestPointer/QuestPointer.lua:252
 QUEST_LOG_UPDATE = <function> defined @QuestPointer/QuestPointer.lua:94
 UpdateLogPOIs = <function> defined @QuestPointer/QuestPointer.lua:126
 dbpc = <table> {
 }
 SUPER_TRACKING_CHANGED = <function> defined @QuestPointer/QuestPointer.lua:499
 FlushDB = <function> defined @QuestPointer/template/Database.lua:13
 poi_parent = Frame {
 }
 InitDB = <function> defined @QuestPointer/template/Database.lua:4
 defaultsPC = <table> {
 }
 GetPOI = <function> defined @QuestPointer/QuestPointer.lua:330
 UpdateEdges = <function> defined @QuestPointer/QuestPointer.lua:499
 SetSelection = <function> defined @QuestPointer/QuestPointer.lua:396
 ADDON_LOADED = <function> defined @QuestPointer/QuestPointer.lua:22
 ResetPOI = <function> defined @QuestPointer/QuestPointer.lua:370
 PLAYER_LOGIN = <function> defined @QuestPointer/QuestPointer.lua:49
 ClearSelection = <function> defined @QuestPointer/QuestPointer.lua:413
 Print = <function> defined @QuestPointer/QuestPointer.lua:538
 UnregisterEvents = <function> defined @QuestPointer/template/EventDispatcher.lua:10
 db = <table> {
 }
 UpdateWorldPOIs = <function> defined @QuestPointer/QuestPointer.lua:192
 ClosestPOI = <function> defined @QuestPointer/QuestPointer.lua:74
 Debug = <function> defined @QuestPointer/template/UtilityFunctions.lua:9
 ZONE_CHANGED_NEW_AREA = <function> defined @QuestPointer/QuestPointer.lua:94
 QUEST_POI_UPDATE = <function> defined @QuestPointer/QuestPointer.lua:94
 TomTomClosestPOI = <function> defined @QuestPointer/TomTom.lua:42
 WorldQuestIsWatched = <function> defined @QuestPointer/QuestPointer.lua:230
 AutoTomTom = <function> defined @QuestPointer/TomTom.lua:15
 QUEST_WATCH_LIST_CHANGED = <function> defined @QuestPointer/QuestPointer.lua:94
 PLAYER_ENTERING_WORLD = <function> defined @QuestPointer/QuestPointer.lua:94
 RegisterEvents = <function> defined @QuestPointer/template/EventDispatcher.lua:9
 RegisterEvent = <function> defined @QuestPointer/template/EventDispatcher.lua:9
 UpdatePOIs = <function> defined @QuestPointer/QuestPointer.lua:94
 UnregisterEvent = <function> defined @QuestPointer/template/EventDispatcher.lua:10
 pois = <table> {
 }
}
mapid = 12
cvar = true
numNumericQuests = 1
numCompletedQuests = 0
numPois = 1
questPois = <table> {
 1 = 65444
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 65444
}
(for control) = 1
i = 1
questId = 65444
_ = false
posX = 0.597438
posY = 0.446914
objective = 0
isOnMap = true
isTask = false
isComplete = false
title = "To the Dragon Isles!"
poiButton = nil
(*temporary) = nil
(*temporary) = Frame {
 0 = <userdata>
}
(*temporary) = 65444
(*temporary) = "numeric"
(*temporary) = 1
(*temporary) = "attempt to call global 'QuestPOI_GetButton' (a nil value)"
Debug = <function> defined @QuestPointer/template/UtilityFunctions.lua:9
ns = <table> {
 PLAYER_LOGOUT = <function> defined @QuestPointer/QuestPointer.lua:64
 defaults = <table> {
 }
 UpdateGlow = <function> defined @QuestPointer/QuestPointer.lua:385
 GetWorldQuestButton = <function> defined @QuestPointer/QuestPointer.lua:252
 QUEST_LOG_UPDATE = <function> defined @QuestPointer/QuestPointer.lua:94
 UpdateLogPOIs = <function> defined @QuestPointer/QuestPointer.lua:126
 dbpc

**Comment by Yinepuhotep** [comment]
Date: 2023-11-16 20:09:56
ID: 157
Error occured in: Global
Count: 6
Message: Interface/AddOns/QuestPointer/QuestPointer.lua line 164:
   attempt to call global 'QuestPOI_GetButton' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: QuestPOI_GetButton()
   [string "@Interface/AddOns/QuestPointer/QuestPointer.lua"]:164: UpdateLogPOIs()
   [string "@Interface/AddOns/QuestPointer/QuestPointer.lua"]:114:
      Interface/AddOns/QuestPointer/QuestPointer.lua:94
   [string "=(tail call)"]: ?
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  KalielsTracker, v6.4.0
  Swatter, v9.1.BETA.5.13 (OneMawTime)
  WowheadLooter, v100200
  Ace3, vr1314
  AckisRecipeList, v9.2.0
  AddonFactory, v10.2.004
  AllTheThings, vDF-3.8.1
  Altoholic, v10.2.004
  Atlas, vv1.52.08
  AtlasBattlegrounds, vv1.52.03
  AtlasBurningCrusade, vv1.52.03
  AtlasCataclysm, vv1.52.03
  AtlasClassicWoW, vv1.52.05
  AtlasClassOrderHalls, vv1.52.04
  AtlasDungeonLocs, vv1.52.04
  AtlasLegion, vv1.52.04
  AtlasMistsofPandaria, vv1.52.04
  AtlasOutdoorRaids, vv1.52.04
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.52.04
  AtlasWarlordsofDraenor, vv1.52.03
  AtlasWorldEvents, vv3.33
  AtlasWrathoftheLichKing, vv1.52.03
  AtlasLoot, vv8.13.14
  Auctioneer, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.13 (OneMawTime)
  BadBoy, vv10.2.0
  BadBoyCCleaner, vv10.2.0
  BadBoyGuilded, vv10.2.0
  BadBoyHistory, vv10.2.0
  BadBoyIgnore, vv10.2.0
  BagBrother, v
  Bagnon, v10.1.15
  BagnonItemInfo, v2.1.68-Release
  Bartender4, v4.14.13
  BattlePetBattleUITweaks, v2.1.10
  CanIMogIt, v10.1.5v1.53
  ColorPickerPlus, v
  CursorTrail, v10.2.0.1
  DataStore, v2023.11.06
  DataStoreAchievements, v2023.11.06
  DataStoreAgenda, v2023.11.06
  DataStoreAuctions, v2023.11.06
  DataStoreCharacters, v2023.11.06
  DataStoreContainers, v2023.11.14
  DataStoreCovenants, v10.2-001
  DataStoreCrafts, v10.2.001
  DataStoreCurrencies, v2023.11.11
  DataStoreGarrisons, v2023.11.06
  DataStoreInventory, v2023.11.06
  DataStoreKeystones, v10.2-001
  DataStoreMails, v2023.11.06
  DataStorePets, v2023.11.06
  DataStoreQuests, v10.2.001
  DataStoreRares, v10.2-001
  DataStoreReputations, v10.2.001
  DataStoreSpells, v2023.11.06
  DataStoreStats, v2023.11.06
  DataStoreTalents, v10.2.001
  DBMArchaeology, vr58
  DBMCore, v83d1e2a
  DBMCountPackOverwatch, v1.4.36
  DBMInterrupts, v2.5.4b
  DBMSoundEventsPack, v1.6.31
  DBMSpellTimers, vr150
  DBMStatusBarTimers, v83d1e2a
  DBMVPVEM, v4a6af0c
  DuelResponse, v6.5.75 (Retail)
  DuelResponseBlacklist, v
  DuelResponseWhisper, v
  Enchantrix, v9.1.BETA.5.13 (OneMawTime)
  FBBroker, v1.39
  FBTitan, v1.0.27
  FBTrackingFrame, v1.22
  FishingBuddy, v1.20.7
  GarrisonCommander, v
  GarrisonCommanderBroker, v
  GatherMate2, v1.48.7
  GTFO, v5.5
  HandyNotes, vv1.6.17
  HandyNotesAdorableRaptorHatchlings, v1.24
  HandyNotesAncientShrines, v10.1.0.7
  HandyNotesAPathLessTravelled, v1.24
  HandyNotesArgus, vv0.39
  HandyNotesBattleForAzeroth, v18
  HandyNotesBattleForAzerothTreasures, vv31
  HandyNotesBoralusRP, v9.0.5.1 (0.360)
  HandyNotesBrokenShore, vv1.52
  HandyNotesBurningCrusade, vv5
  HandyNotesCollection, v
  HandyNotesCovenantSanctum, vv23
  HandyNotesDarkSoilTillers, v3.37
  HandyNotesDraenor, v3.6
  HandyNotesDraenorTreasures, v1.21
  HandyNotesDragonflight, v44
  HandyNotesDragonflightTreasures, vv53
  HandyNotesDragonGlyphs, v0.1.0
  HandyNotesDungeonLocations, v2.1a
  HandyNotesEAPandaria, v1.33
  HandyNotesFerryNetwork, vv1.3.12
  HandyNotesHallowsEnd, v2.25
  HandyNotesHigherLearning, v1.28
  HandyNotesKosumoth, vv8
  HandyNotesLegionClassOrderHalls, vv1.51
  HandyNotesLegionInstanceWorldQuests, vv1.36
  HandyNotesLegionMagePortals, v2.6
  HandyNotesLegionTreasures, vv34
  HandyNotesLongForgottenHippogryph, v1.20
  HandyNotesLoosePebbles, v1.21
  HandyNotesLorewalkers, vv14
  HandyNotesLunarFestival, v2.07
  HandyNotesMistsOfPandariaTreasures, vv26
  HandyNotesMythicPlus, vV100105-0
  HandyNotesNetherwingEggs, v2.03
  HandyNotesNobleGarden, v2.10
  HandyNotesOribos, vv28
  HandynotesPandaria, v1.5.11
  HandyNotesScarabCoffers, v10
  HandyNotesSecretFish, vv5
  HandyNotesShadowlands, v58
  HandyNotesShadowlandsTreasures, vv74
  HandyNotesSpringfurAlpaca, v1.23
  HandyNotesStygia, vv100200.0
  HandyNotesSuramarShalAranTelemancy, vv1.44
  HandyNotesSuramarTelemancy, vv12
  HandyNotesTimelessIsleChests, v1.24d
  HandyNotesTravelGuide, vv2.14.5
  HandyNotesTreasureHunter, vv34
  HandyNotesUniversalExplorer, v10.0.2.1
  HandyNotesValdrakken, vv9
  HandyNotesWinterVeil, v1.15
  HandyNotesWitheredArmyTraining, v1
  HandyNotesWorldMapButton, v100200.01-Release
  HandyNotesWrathOfTheLichKing, vv13
  Healium, v
  Hyperlegible, v1.1.2
  IceHUD, vv1.14.29
  Informant, v9.1.BETA.5.13 (OneMawTime)
  KrowiAchievementFilter, v60.2
  KuiMedia, v
  KuiNameplates, v2.29.11
  KuiNameplatesCore, v
  KuiNameplatesElite, vv2.15
  LeatrixMaps, v10.2.01
  LFHWaypoints, v1.0.10
  LightHeaded, vv100002-1.0.0-2022-12-15
  MacroToolkit, vv2.2.3
  MacroToolkitIcons, vv2.2.3
  MikScrollingBattleText, v5.9.0
  MinimapButtonButton, v1.17.5
  MiniMapLine, v1.1.1
  MissingFlightPaths, v2.0.0
  MountsJournal, vv10.2.3
  MyPathfinder, v3.8.10
  NigglesPetTeams, v5.04
  OmniCC, v10.2.0
  Outfitter, v10.2.0.0
  ParagonReputation, v1.50
  Pawn, v2.8.3
  PetCare, v6.6.1 100100
  PetTracker, v10.1.1
  PetTrackerJournal, v
  Prat30, v3.9.32
  Prat30Libraries, v
  QuestCompletist, v109.44
  QuestPointer, vv29
  Rarity, v1.0 (r726-release)
  RarityOptions, v
  Rematch, v5.0.1
  RematchTSMPetValues, v1.2.1
  RepByZone, v1.33.6
  Routes, vv1.7.4
  RoutesImportExport, vv1.0.7
  SharedMedia, v3.1.1-199
  SharedMediaCausese, v
  SharedMediaClassicalFonts, v2.0.25
  SharedMediaAdditionalFonts, v10.0.5
  SilverDragon, vv2023.10
  SilverDragonOverlay, vv2023.10
  SilverDragonRangeExtender, vv2023.10
  Skillet, v5.21
  SlideBar, v9.1.BETA.5.13 (OneMawTime)
  SmartError, v2.0.1
  SpartanUI, v6.2.21
  Stubby, v9.1.BETA.5.13 (OneMawTime)
  TankMD, vv2.5.1
  TipTac, v23.11.06
  TipTacItemRef, v23.11.06
  TipTacTalents, v23.11.06
  Titan, v7.01.04.100200
  TitanBag, v7.01.04.100200
  TitanClock, v7.01.04.100200
  TitanCurrenciesMulti, vv9.16.0
  TitanGold, v7.01.04.100200
  TitanLocation, v7.01.04.100200
  TitanLootType, v7.01.04.100200
  TitanMail, v10.0.2.0
  TitanOutfitter, v
  TitanPerformance, v7.01.04.100200
  TitanProfessionsMulti, vv9.2.5
  TitanReloadUI, v1.0
  TitanRepair, v7.01.04.100200
  TitanReputations, vv1.40
  TitanRestPlus, v9.0.1.1
  TitanShard, v4.3.1.30300
  TitanVolume, v7.01.04.100200
  TitanXP, v7.01.04.100200
  TomPoints, v100105_26
  TomTom, vv3.5.4-release
  totalRP3, v2.6.2
  totalRP3Data, v2.6.2
  totalRP3Extended, v2.0.3
  totalRP3ExtendedImpExport, v2.0.3
  totalRP3ExtendedTools, v2.0.3
  TradeSkillMaster, vv4.13.16
  TradeSkillMasterAppHelper, vv4.13
  VenturePlan, v4.40b
  VenturePlanMoreFollowers, v14
  BlizRuntimeLib v10.2.0.52188(US) <enUS>
  (ck=1979)

**Comment by kemayo** [comment]
I'll admit, that took me a while to get fixed.

**Comment by allogator** [comment]
> I'll admit, that took me a while to get fixed.

Hey, I was finally able to enable one of my favorite addons so I'll take it!
