### ISSUE TITLE
QuestPointer has been blocked from an action only available to the Blizzard UI

### ISSUE THREAD

**Issue by petejk2** [kemayo/wow-questpointer#6]
When selecting a quest item to use from the objective tracker, I receive the error "QuestPointer has been blocked from an action only available to the Blizzard UI".

I am using QuestPointer v31.

Two quest items I have tried are those from 'Carp Care', and 'The War Within'

**Comment by kemayo** [comment]
That seems to have fixed it for me, at least.

**Comment by petejk2** [comment]
Great, thanks for the fix!
I've tested the new version on another couple of quests with items with no issues.
Cheers
